### ISSUE TITLE
some error in python3.6   system ubuntu16.04LTS 

### ISSUE THREAD

**Issue by CrazyIEEE** [liu-yun/wisdomtree#11]
Traceback (most recent call last):
  File "study.py", line 131, in <module>
    save_record(section, True)
  File "study.py", line 105, in save_record
    if f'L{dic["id"]}' in studied and studied[f'L{dic["id"]}']['watchState'] == 1:
TypeError: argument of type 'NoneType' is not iterable

**Comment by yunv** [comment]
Please try the latest version.

**Comment by CrazyIEEE** [comment]
File ".\study.py", line 131, in <module>
    save_record(section, True)
  File ".\study.py", line 112, in save_record
    'recruitId': recruit_id, 'chapterId': dic['chapterId'], 'sourseType': 3, 'playTimes': video_time,
KeyError: 'chapterId'

**Comment by CrazyIEEE** [comment]
every nice thanks
