### ISSUE TITLE
Crashes after 'videos done'

### ISSUE THREAD

**Issue by Lagrand** [liu-yun/wisdomtree#4]
With the recently updated version, videos are done perfectly, but the script crashes while doing exams.
Details:
```
Traceback (most recent call last):
  File "study.py", line 187, in <module>
    for question in r.json()['rt']['examList']:
KeyError: 'rt'
```
I have tried four times in two courses (two times each). The log above was printed three times, and the log below was printed one time.
```
Traceback (most recent call last):
  File "study.py", line 223, in <module>
    d = json.loads(r.text.replace('"{', '{').replace('}"', '}').replace('\\', ''))['rt']
KeyError: 'rt'
```

**Comment by liu-yun** [comment]
Can you do the exam in the app?
