### ISSUE TITLE
Should I open the website to make the exam begin?

### ISSUE THREAD

**Issue by Sakakibara-Hu** [liu-yun/wisdomtree#5]
It's time to do the exam, but it can't work.
Like this:
```
2017-05-27 12:18:07,394 INFO     Videos done.
2017-05-27 12:18:07,550 INFO     营养与食疗学教程考试
Traceback (most recent call last):
  File "study.py", line 173, in <module>
    ids = post(SIGN, '/student/exam/examQuestionIdListByCache', p)['examList']
KeyError: 'examList'
```

Should I open the website to make the exam begin? Like this?
![image](https://cloud.githubusercontent.com/assets/26788881/26517989/e6c50780-42d7-11e7-8cd4-67d279bddedd.png)

**Comment by liu-yun** [comment]
No, you don't need to start it on web.
I've just tested a new course with no issues. Would you like to provide your `userinfo.py`?

**Comment by Sakakibara-Hu** [comment]
Yeah, Fine. Where should I upload it?

**Comment by liu-yun** [comment]
You can use gist.github.com

**Comment by Sakakibara-Hu** [comment]
I created a secreat gist, but how do I show you the url?（[为什么不好好说中文- -](https://gist.github.com/Sakakibara-Hu/30acdaa26aedbca902374b9c6c650754)）

**Comment by liu-yun** [comment]
Fixed.
